services:
  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - ${SERVER_PORT}:3000

    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    container_name: postgres
    image: postgres:16.6-alpine3.21
    env_file:
      - ./backend/.env
    ports:
      - ${POSTGRES_PORT}:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

    restart: always
