// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: endpoint.sql

package storage

import (
	"context"
)

const exampleEndpoint = `-- name: ExampleEndpoint :exec
select (1) from endpoints
`

func (q *Queries) ExampleEndpoint(ctx context.Context) error {
	_, err := q.db.Exec(ctx, exampleEndpoint)
	return err
}
