// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Endpoint struct {
	ID          uuid.UUID
	Done        bool
	Name        string
	Path        string
	Method      string
	Description string
	ShemaID     pgtype.UUID
}

type Project struct {
	ID          uuid.UUID
	Name        string
	CreatorID   uuid.UUID
	Desctiption string
}

type ProjectMember struct {
	MemberID  uuid.UUID
	ProjectID uuid.UUID
}

type Sheme struct {
	ID         uuid.UUID
	ProjectID  pgtype.UUID
	ServiceTag string
	NeedsAuth  bool
	Name       string
	Details    []byte
}

type User struct {
	ID       uuid.UUID
	Name     string
	Password string
}
