// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: project.sql

package storage

import (
	"context"
)

const exampleProject = `-- name: ExampleProject :exec
select (1) from projects
`

func (q *Queries) ExampleProject(ctx context.Context) error {
	_, err := q.db.Exec(ctx, exampleProject)
	return err
}
